name: test-and-build

on: [push]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Run Unit Tests
        run: yarn test:unit
        env:
          COVERAGE: true
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  feat-tests:
    name: Run Feature Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Run Feature Tests
        run: yarn test:feat
        env:
          CI: true

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build
        run: yarn build --modern
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_UPLOAD_SOURCE_MAPS: true
          VUE_APP_SENTRY_DSN: ${{ secrets.VUE_APP_SENTRY_DSN }}

      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ github.sha }}
          path: dist

      - name: Publish on Netlify (preview)
        run: |
          yarn netlify --telemetry-disable
          yarn netlify deploy --dir=dist --alias ${{ github.sha }} --message='${{ github.sha }}::${{ github.actor }}::${{ github.ref }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  e2e-tests:
    name: Run E2E Tests
    needs: [build]
    runs-on: ubuntu-16.04
    container:
      image: cypress/browsers:node12.14.1-chrome85-ff81
      options: "--shm-size=2GB"
      env:
        CYPRESS_BASE_URL: 'https://${{ github.sha }}--photion.netlify.app'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Install Cypress
        run: yarn cypress install

      - name: Run E2E Tests
        run: yarn cypress run --browser chrome --config videoUploadOnPasses=false

      - name: Upload cypress videos folder
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos-${{ github.sha }}
          path: cypress/videos


  publish-netlify:
    name: Publish on Netlify (production)
    if: github.ref == 'refs/heads/master'
    needs: [build, unit-tests, feat-tests, e2e-tests]
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Download dist folder
        uses: actions/download-artifact@v2
        with:
          name: dist-${{ github.sha }}
          path: dist

      - name: Publish on Netlify (production)
        run: |
          yarn netlify --telemetry-disable
          yarn netlify deploy --dir=dist --prod --message='${{ github.sha }}::${{ github.actor }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
